# Generated by Django 4.2.5 on 2023-09-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0002_estudiante"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entregables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("fecha_entrega", models.DateField()),
                ("entregado", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Profesores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=40)),
                ("apellido", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
                ("profesion", models.CharField(max_length=40)),
            ],
        ),
    ]
