# Generated by Django 4.2.4 on 2023-09-09 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0003_entregables_profesores"),
    ]

    operations = [
        migrations.AddField(
            model_name="entregables",
            name="link",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
